[tool.ruff]
exclude = ['.venv']

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = [
    "ERA001",
    "RUF00",
    "Q000",
    "FA102",
    "D205",
    "D400",
    "D415",
    "S104",
    "TRY300",
    "TRY401",
    "G004",
    "RET503",
    "D203",
    "D212",
    "COM812",
    "ISC001",
    "Q000",
    "Q003",
    "TC001",
    "S608",
    "FIX",     # фиксы
    "TD",      # туду
    "N815",    # кейс
    "T20",     # принт
    "DTZ005",  # timezone
    "DTZ011",  # timezone2
    "D10",     # докстринги
    "ANN",     # аннотации
    "E501",    # длина строки
    "PLR0913", # много аргументов
    "FBT",     # булеаны
    "ARG001",  # неиспользуемый аргумент
    "BLE001",  # Exception
    "PGH004",  # noqa
    "RUF012",  # дженерики
    "TRY400",  # logging.error
    "B904",    # except from
    "PLE1205", # loguru
    "E712",    # boolean
    "TC00",    # type checking
]

[tool.ruff.format]
quote-style = "single"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
combine_as_imports = true
order_by_type = false
force_single_line = false
